# Generated by Django 5.2.7 on 2025-10-12 07:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('word_count', models.PositiveBigIntegerField()),
                ('study_time', models.PositiveBigIntegerField()),
                ('study_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'study_timestamp'], name='llrecord_user_id_study_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'idempotency_key'), name='uniq_user_id_idemkey')],
            },
        ),
    ]
